
package client.rent;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRentWebService", targetNamespace = "http://superbiz.org/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRentWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns client.rent.RentSoapDto
     * @throws RentNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRent", targetNamespace = "http://superbiz.org/wsdl", className = "client.rent.GetRent")
    @ResponseWrapper(localName = "getRentResponse", targetNamespace = "http://superbiz.org/wsdl", className = "client.rent.GetRentResponse")
    @Action(input = "http://superbiz.org/wsdl/IRentWebService/getRentRequest", output = "http://superbiz.org/wsdl/IRentWebService/getRentResponse", fault = {
        @FaultAction(className = RentNotFoundException_Exception.class, value = "http://superbiz.org/wsdl/IRentWebService/getRent/Fault/RentNotFoundException")
    })
    public RentSoapDto getRent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws RentNotFoundException_Exception
    ;

}
