
package client.rent;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RentService", targetNamespace = "http://superbiz.org/wsdl", wsdlLocation = "http://localhost:8080/tks-soap/RentService?wsdl")
public class RentService
    extends Service
{

    private final static URL RENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException RENTSERVICE_EXCEPTION;
    private final static QName RENTSERVICE_QNAME = new QName("http://superbiz.org/wsdl", "RentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/tks-soap/RentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RENTSERVICE_WSDL_LOCATION = url;
        RENTSERVICE_EXCEPTION = e;
    }

    public RentService() {
        super(__getWsdlLocation(), RENTSERVICE_QNAME);
    }

    public RentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RENTSERVICE_QNAME, features);
    }

    public RentService(URL wsdlLocation) {
        super(wsdlLocation, RENTSERVICE_QNAME);
    }

    public RentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RENTSERVICE_QNAME, features);
    }

    public RentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRentWebService
     */
    @WebEndpoint(name = "RentPort")
    public IRentWebService getRentPort() {
        return super.getPort(new QName("http://superbiz.org/wsdl", "RentPort"), IRentWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRentWebService
     */
    @WebEndpoint(name = "RentPort")
    public IRentWebService getRentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://superbiz.org/wsdl", "RentPort"), IRentWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RENTSERVICE_EXCEPTION!= null) {
            throw RENTSERVICE_EXCEPTION;
        }
        return RENTSERVICE_WSDL_LOCATION;
    }

}
