
package client.rent;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RentNotFoundException", targetNamespace = "http://superbiz.org/wsdl")
public class RentNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RentNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RentNotFoundException_Exception(String message, RentNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RentNotFoundException_Exception(String message, RentNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.rent.RentNotFoundException
     */
    public RentNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
