micronaut:
  server:
    port: 8083
  application:
    name: microservicesLibrary
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:postgresql://db:5432/libraryDB
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update

kafka:
  bootstrap:
#    servers: host.docker.internal:9093
    servers: tkskafka.eastus.azurecontainer.io:9093
