FROM payara/micro:jdk11
ENV PAYARA_ARGS --debug
COPY target/rent-service.war $DEPLOY_DIR
COPY target/dependency/kafka-rar-0.5.0.rar $DEPLOY_DIR
# ENV JAVA_DEBUG_PORT="*:9009"
# ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:9009", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=90.0", "-jar", "payara-micro.jar"]
CMD ["--deploymentDir", "/opt/payara/deployments", "--port", "8090"]