
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserWebService", targetNamespace = "http://superbiz.org/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns client.UserSoapDto
     * @throws UserNotFoundException_Exception
     * @throws TypeValidationFailedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://superbiz.org/wsdl", className = "client.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://superbiz.org/wsdl", className = "client.GetUserResponse")
    @Action(input = "http://superbiz.org/wsdl/IUserWebService/getUserRequest", output = "http://superbiz.org/wsdl/IUserWebService/getUserResponse", fault = {
        @FaultAction(className = UserNotFoundException_Exception.class, value = "http://superbiz.org/wsdl/IUserWebService/getUser/Fault/UserNotFoundException"),
        @FaultAction(className = TypeValidationFailedException_Exception.class, value = "http://superbiz.org/wsdl/IUserWebService/getUser/Fault/TypeValidationFailedException")
    })
    public UserSoapDto getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws TypeValidationFailedException_Exception, UserNotFoundException_Exception
    ;

}
