
package client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TypeValidationFailedException", targetNamespace = "http://superbiz.org/wsdl")
public class TypeValidationFailedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TypeValidationFailedException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TypeValidationFailedException_Exception(String message, TypeValidationFailedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TypeValidationFailedException_Exception(String message, TypeValidationFailedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.TypeValidationFailedException
     */
    public TypeValidationFailedException getFaultInfo() {
        return faultInfo;
    }

}
